/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv ./cloudflare-env.d.ts` (hash: 7756c045603a6e893d436cc058f6e054)
// Runtime types generated with workerd@1.20260131.0 2025-12-01 global_fetch_strictly_public,nodejs_compat
declare namespace Cloudflare {
  interface Env {
    IMAGES: ImagesBinding;
    ASSETS: Fetcher;
    NEXTJS_ENV: string;
    WORKER_SELF_REFERENCE: Fetcher /* frontend */;
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
