/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: b739a9c19cff1463949c4db47674ed86)
// Runtime types generated with workerd@1.20260131.0 2026-01-31
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  type Env = {};
}
interface Env extends Cloudflare.Env {}
