/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings` (hash: 3e61d0e421dcf6794aface07d4dabaf6)
// Runtime types generated with workerd@1.20260131.0 2025-09-27
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env {
    ASSETS: Fetcher;
  }
}
interface CloudflareBindings extends Cloudflare.Env {}
